version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21.3.0
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: tharun
      APP_USER: tharun
      APP_USER_PASSWORD: tharun
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata


  bank-app:
    build: .
    container_name: bank-app
    depends_on:
      - oracle-db
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - .:/app   
  frontend:
    build:
      context: ./frontend
    container_name: bank-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - bank-app

volumes:
  oracle_data:
 