version: '3.11'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21.3.0
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: tharun
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata 

  bank-app:
    build: .
    container_name: bank-app
    depends_on:
      - oracle-db
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  oracle_data:
