name: Python CI with Oracle and auto testing on push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services: 
       oracle:
          image: gvenzl/oracle-xe:21.3.0
          env:
            ORACLE_PASSWORD: tharun
          ports:
             - 1521:1521

    steps:
      - name: checkout  
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Oracle Instant Client 19.8
        run: |
          sudo apt-get update
          sudo apt-get install -y libaio-dev unzip wget
          wget https://download.oracle.com/otn_software/linux/instantclient/19800/instantclient-basiclite-linux.x64-19.8.0.0.0dbru.zip
          unzip instantclient-basiclite-linux.x64-19.8.0.0.0dbru.zip -d oracle_client
          echo "$HOME/oracle_client/instantclient_19_8" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$HOME/oracle_client/instantclient_19_8" >> $GITHUB_ENV
          echo "$HOME/oracle_client/instantclient_19_8" | sudo tee /etc/ld.so.conf.d/oracle-instantclient.conf
          sudo ldconfig
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set DB env variable
        run: |
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=1521" >> $GITHUB_ENV
          echo "DB_SERVICE=XEPDB1" >> $GITHUB_ENV
          echo "DB_USER=tharun" >> $GITHUB_ENV
          echo "DB_PASSWORD=tharun" >> $GITHUB_ENV
      - name: wait for oracle to intialize
        run: |
          echo "waiting"
          sleep 90
      - name: Run test_api
        run: |
          PYTHONPATH=. pytest test_api.py -v
