name: Python CI with Oracle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Oracle Instant Client
        run: |
          sudo apt-get update
          sudo apt-get install -y libaio1
          wget https://download.oracle.com/otn_software/linux/instantclient/211000/instantclient-basiclite-linux.x64-21.10.0.0.0dbru.zip
          unzip instantclient-basiclite-linux.x64-21.10.0.0.0dbru.zip
          sudo mkdir -p /opt/oracle
          sudo mv instantclient_21_10 /opt/oracle/
          echo "/opt/oracle/instantclient_21_10" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/opt/oracle/instantclient_21_10" >> $GITHUB_ENV
          echo "ORACLE_HOME=/opt/oracle/instantclient_21_10" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest cx_Oracle
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests
        run: |
          PYTHONPATH=. pytest test_bank.py -v --cov=bank --cov-report=xml
