name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:  # Changed from 'build' to 'test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Updated to v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'  # Faster installs
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run unit tests
        run: |
          PYTHONPATH=. pytest test_bank.py -v --cov=bank --cov-report=xml
          
      - name: Upload coverage
        uses: codecov/codecov-action@v3