name: Python CI with Oracle and auto testing on push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services: 
       oracle:
          image: gvenzl/oracle-xe:21.3.0
          env:
          ORACLE_PASSWORD: tharun
          ports:
             - 1521:1521

    steps:
      - name: checkout  
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set DB env variable
        run: |
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=1521" >> $GITHUB_ENV
          echo "DB_SERVICE=XEPDB1" >> $GITHUB_ENV
          echo "DB_USER=tharun" >> $GITHUB_ENV
          echo "DB_PASSWORD=tharun" >> $GITHUB_ENV
      - name: wait for oracle to intialize
        run: |
          echo "waiting"
          sleep 90
      - name: Run test_api
        run: |
          PYTHONPATH=. pytest test_api.py -v
